pagination_per_page: 30
vat_rate: 18
default_currency: :ugx
opportunity_notify:
 - :ceo
 - :program_coordinator
 - :admin

user_creation_notify:
 - :ceo
 - :admin

can_see_general_dashboard:
  - :admin
  - :ceo
  - :finance