#If key `accessible:` is left out, it is assumed that
#the user has access to the menu
system_menu:
  Dashboard:
    path: '/'
    icon: 'icon-home'
  Sales:
    icon: 'icon-basket'
    accessible: :all
    submenus:
      Opportunities:
        path: '/opportunities/'
        icon:
        accessible: :all
      Training:
        path: '/trainings/'
        icon:
        accessible:
          - :superadmin
          - :admin
          - :ceo
          - :program_coordinator
          - :finance
      Admissions:
        path: '#'
        icon:
        accessible:
          - :superadmin
          - :admin
          - :ceo
          - :program_coordinator
          - :finance
      ClientsList:
        path: '/organisations/'
        icon:
        accessible: :all
      ProgramsList:
        path: '/programs/'
        icon:
        accessible: :all
      ParticipantsList:
        path: '/participants/'
        icon:
        accessible: :all
  Marketing:
    path:
    icon: 'icon-diamond'
    accessible: :all
    submenus:
      MassMailings:
        path: '#'
        icon:
        accessible: :all
      MailingLists:
        path: '#'
        icon:
        accessible: :all
      MarketingEvents:
        path: '#'
        icon:
        accessible: :all
  Work:
    icon: 'icon-briefcase'
    accessible:
      - :superadmin
      - :ceo
      - :finance
      - :manager
    submenus:
      Rfqs/Rfps:
        path: '/rfqs/'
        icon:
        accessible: :all
      Tasks:
        path: '/tasks/'
        icon:
        accessible: :all
  Accounts:
    icon: 'icon-calculator'
    accessible:
        - :superadmin
        - :ceo
        - :finance
    submenus:
      Invoices:
        path: '/accounts_invoices/'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
      Expenses:
        path: '/expenses/'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
      Purchase Orders:
        path: '#'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
      Store:
        path: '#'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
      Assets:
        path: '/cpny/assets/'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
      SuppliersList:
        path: '/suppliers/'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
  HumanResources:
    path:
    icon: 'icon-users'
    accessible: :all
    submenus:
      EmployeesList:
        path: '/users/'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
      Contracts:
        path: '#'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
      Loans:
        path: '#'
        icon:
        accessible:
          - :superadmin
          - :ceo
          - :finance
      Leave:
        path: '#'
        icon:
        accessible: :all
      Claims:
        path: '#'
        icon:
        accessible: :all
  Settings:
      path:
      icon: 'icon-settings'
      accessible:
        - :superadmin
        - :admin
        - :ceo
      submenus:
        Countries:
          path: '/countries/'
          icon:
          accessible:
            - :superadmin
            - :admin
            - :ceo
        Users:
          path: '/users/'
          icon:
          accessible:
            - :superadmin
            - :ceo
        ProgramCategories:
          path: '/categories/'
          icon:
          accessible:
            - :superadmin
            - :admin
            - :ceo