supplies_items_list:
  Desk supplies:
    - Pens
    - Pencils
    - Markers
    - Highlighters
    - Paper clips
    - Tape
    - Rubber bands
    - Erasers
    - Stamp pads
    - Ink for stamp pads
    - Paper products
  Spiral notebooks:
    - Writing pads
    - Post–it notes
    - Phone message pads
    - Laser printer paper
    - Copy paper
    - Fax paper
    - Graph paper
    - Colored paper
    - Pocket notebook
  Filing supplies:
    - Manila file folders
    - Hanging file folders
    - Pocket folders
    - File labels
    - Index dividers
    - Tabs
  Stationery:
    - Letter envelopes
    - Catalog envelopes
    - Padded envelopes
    - Shipping paper
    - Shipping labels
    - Disk mailers
    - Bubble wrap
    - Sealing tape
  Computer and Printer:
    - Toner cartridges
    - Flash disks
    - CD–Roms
    - Zip drive tapes
    - Projectors
    - Mouse
    - Computer Cables
    - Flash disks
    - Computer Monitors
    - Laptops
    - Keyboards
  Time tracking supplies:
    - Calendar
    - Refills for planner
    - Time cards
    - Scheduling boards
    - To–do lists
  Binding supplies:
    - Staples
    - Bulldog clamps
    - Fasteners
    - Glue
    - Glue sticks
    - Reinforcements
    - 3–ring binders
  Supplies for hanging:
    - Pushpins
    - Thumbtacks
    - Map pins
    - Masking Tape
  Identification supplies:
    - Price tags
    - Name badges
    - Labels
    - Color coding labels