user_menu:
  UserHome:
    path: '/'
    icon: 'icon-home'
  Messages:
    path: "/mailbox/inbox"
    icon: 'fa fa-inbox'
  Tasks:
    path: '#'
    icon: 'icon-check'
  AccountSettings:
    path: '#'
    icon: 'icon-settings'
  Help:
    path: '#'
    icon: 'icon-info'